config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users

  authenticated :user do
    root :to => 'home#index', :as => :authenticated_root
  end
  root :to => redirect('/users/sign_in')  

  resources :users
  post 'users/reset_password/:id', to: 'users#reset_password'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, :all
    end    
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable

  validates_presence_of     :login, :email
  validates_uniqueness_of   :login,     :case_sensitive => false, :allow_blank => true, :if => :login_changed?
  validates_format_of       :email, :with  => Devise.email_regexp, :allow_blank => true, :if => :email_changed?
  validates_presence_of     :password, if: :password_required?
  validates_confirmation_of :password, if: :password_required?
  validates_length_of       :password, :within => Devise.password_length, :allow_blank => true
  validates_presence_of     :role, :on=>:create

  enum role: [:guest, :admin]

  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :guest
  end

  def password_required?
    persisted? && reset_password_token.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to '/home/index', :alert => exception.message
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def upload
    "dupa"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
    authorize! :read, User, :message => "You are not allowed to see users."
  end

  def show
    @user = User.find(params[:id])
    authorize! :read, User, :message => "You are not allowed to see user."
  end

  def new
    @user = User.new
    authorize! :create, User, :message => "You are not allowed to create new user."
  end

  def create    
    @user = User.new(params.require(:user).permit!)
    authorize! :create, User, :message => "You are not allowed to create new user."
    if @user.save
      @user.send_reset_password_instructions
      respond_to do |format|
        format.html { redirect_to users_path, notice: "User was successfully created. Reset password instructions have been sent to #{@user.email}" }
      end
    else
      flash[:error] = "Unable to add new user due to validation errors"
      respond_to do |format|
        format.html { render action: "new"   }
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    authorize! :create, User, :message => "You are not allowed to modify user."
  end

  def destroy
    authorize! :create, User, :message => "You are not allowed to destroy user."
    begin
      user = User.destroy(params[:id])
      flash[:notice] = "#{user.login} has been removed successfully"
    rescue => e
      flash[:error] = "Unable to remove user because of '#{e.message}' error"
    end
    redirect_to users_path
  end

  def reset_password
    begin
      user = User.find(params[:id])
      user.send_reset_password_instructions
      model = {:type => :info, :message => "Reset password instructions have been sent to #{user.email}"}
    rescue => e
      model = {:type => :error, :message => "Couldn't sent reset password instructions because of #{e}"}
    end
    #redirect_to users_path
    respond_to do |format|
    format.json{
      render :json => model.to_json
    }
  end    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def application_name
    "Smartagent"
  end

  def bootstrap_class_for flash_type
    case flash_type.to_sym
    when :success
      "alert-success"
    when :error
      "alert-danger"
    when :alert
      "alert-warning"
    when :notice
      "alert-info"
    else
      flash_type.to_s
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.haml
.jumbotron
  .container
    %h1 Witaj! 
    %p Załaduj raport z everest
    %p
      %a.btn.btn-primary.btn-lg{ role: "button"} Załaduj

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Smartagent"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    - if user_signed_in?            
      .navbar.navbar-inverse.navbar-default
        .container
          %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand(href="#")
            =application_name
          .navbar-collapse.collapse.navbar-responsive-collapse
            %ul.nav.navbar-nav
              %li= link_to "Users", controller: :users, action: :index
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"
              %li= link_to "Link 3", "/path3"
            %p.navbar-text.navbar-right
              %a.navbar-link(href="javascript:void(0)") 
                = current_user.login
              = link_to('Logout', destroy_user_session_path, :method => :delete, :class => "navbar-link")
    #flash_notice
      - unless flash.empty?
        .container
          - flash.each do |type, message|
            %div{:class => "alert #{bootstrap_class_for(type)} alert-dismissible", :role => "alert"}
              %button.close{:"data-dismiss" => "alert"}x
              =message
    = yield
    %footer
      %p &copy; Smartagent 2014

app/views/users/_form.html.haml
%h2 New User
= form_for @user, html: {class: "form-horizontal" } do |f|
  %fieldset
    .form-group
      = f.label :login, class: "control-label col-sm-2"
      .col-sm-4
        = f.text_field :login, class: "form-control", placeholder: "Login"
    .form-group
      = f.label :email, class: "control-label col-sm-2"
      .col-sm-4
        = f.email_field :email, class: "form-control", placeholder: "Email"
    .form-group
      = f.label :role, class: "control-label col-sm-2"
      .col-sm-4
        = f.select :role, options_for_select(User.roles.collect { |s| [s[0].humanize, s[0]] }, selected: @user.role), {} , class: "form-control"
    = f.submit class: "btn btn-primary"

app/views/users/edit.html.haml
.container
  = render :partial => 'form'

app/views/users/index.html.haml
.container
  %h2 Users
  = link_to 'New', new_user_path, :class => 'btn btn-primary'
  %table.table.table-hover
    %thead
      %tr
        %th ID
        %th Login
        %th Email
        %th Role
        %th Signed In Count
        %th Actions
    %tbody
    - @users.each do |user|
      %tr
        %td
          = user.id
        %td
          = link_to user.login, user_path(user)
        %td
          = user.email
        %td
          = user.role
        %td
          = user.sign_in_count
        %td
          %a.reset_passwd.btn.btn-primary.btn-sm.ladda-button{"href" => '#', "data-style" => "zoom-in", "data-size" => "l", "data" => {"id" => user.id}}
            %span.ladda-label Reset Password 
          = link_to 'Show', user_path(user), :class => 'btn btn-sm btn-info'
          = link_to 'Destroy', user_path(user), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-sm btn-danger'

app/views/users/new.html.haml
.container
  = render :partial => 'form'

app/views/users/show.html.haml
.container
  = render :partial => 'form'